source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
link_with 'CardsBusiness', 'CardsBusinessIH'


#网络
pod 'Reachability', '3.2'
pod 'AFNetworking', '~> 2.6.3'
#图片
pod 'SDWebImage'
#统计
pod 'Bugly', '1.4.1'
pod 'UMengAnalytics-NO-IDFA', '3.6.5'

#加载动画
pod 'MBProgressHUD', '~> 0.8'
#刷新
pod 'MJRefresh', '2.0.2'
#数据库
pod 'FMDB'

#类扩展
pod 'Mantle', '~> 1.5'
pod 'libextobjc'

#百度地图
pod 'BaiduMapKit', '~> 2.9.1'

#加密
#pod pod 'SSKeychain', '1.2.3'

#条形码
pod 'ZXingObjC', '3.1.0'

#pod 'Toast'
#pod 'SVPullToRefresh'
#pod 'INTULocationManager'
#pod 'Masonry'
#pod 'iCarousel'
#pod 'HPGrowingTextView', '~> 1.1'
#pod 'CHTCollectionViewWaterfallLayout'
#pod 'JRSwizzle'
#pod 'IQKeyboardManager', '~> 3.2.1.1'
#pod "Qiniu", "~> 7.0"
#pod 'CLImageEditor'
#pod 'EaseMobSDK', '~> 2.1.6'
#pod 'PureLayout', '~> 2.0.6'
#pod 'SSKeychain', '1.2.3'`
#pod 'Objective-LevelDB'
#pod 'HMSegmentedControl','~> 1.4.0'
#pod 'SVSegmentedControl'